DROP DATABASE IF EXISTS Testing_System_Assignment_1;

CREATE DATABASE Testing_System_Assignment_1;

USE Testing_System_Assignment_1;

DROP TABLE IF EXISTS `Department`;
CREATE TABLE `Department` (
	DepartmentId		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    DepartmentName		VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS `Position`;
 CREATE TABLE  `Position` (
	PositionID		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PositionName	VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS `Account`;
  CREATE TABLE `Account` (
	AccountID		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Email			VARCHAR(100) NOT NULL, 
    Username 		VARCHAR(100),
    FullName		VARCHAR(100) NOT NULL,
    DepartmentID  	TINYINT UNSIGNED NOT NULL ,
    PositionID		TINYINT UNSIGNED NOT NULL,
    CreateDate  	DATETIME,
    CONSTRAINT FOREIGN KEY (DepartmentID) REFERENCES `Department`(DepartmentID),
    CONSTRAINT FOREIGN KEY (PositionID) REFERENCES `Position`(PositionID)
    );
    
DROP TABLE IF EXISTS  `Group`;
  CREATE TABLE  `Group`  (
    GroupID			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    GroupName		VARCHAR(100) NOT NULL,
    CreatorID		SMALLINT UNSIGNED ,
    CreateDate		DATETIME
    );
    
DROP TABLE IF EXISTS `GroupAccount`;
  CREATE TABLE 	`GroupAccount` (
    GroupID 		TINYINT UNSIGNED PRIMARY KEY,
    AccountID		TINYINT UNSIGNED NOT NULL,
    JoinDate		DATETIME,
    CONSTRAINT FOREIGN KEY (AccountID) REFERENCES `Account` (AccountID)
);
    
DROP TABLE IF EXISTS `TypeQuestion`;
CREATE TABLE	`TypeQuestion` (
	TypeID			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	TypeName		ENUM('Essay', 'Multiple-Choice') NOT NULL
);

DROP TABLE IF EXISTS `CategoryQuestion`;
CREATE TABLE	`CategoryQuestion` (
	CategoryID		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CategoryName	VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS `Question`;
CREATE TABLE `Question` (
	QuestionID			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Content				VARCHAR(1000) NOT NULL,
	CategoryID			TINYINT UNSIGNED NOT NULL,
	TypeID				TINYINT UNSIGNED NOT NULL,
	CreatorID			INT NOT NULL,
	CreateDate			DATETIME,
    CONSTRAINT FOREIGN KEY  (CategoryID) REFERENCES `CategoryQuestion` (CategoryID),
    CONSTRAINT FOREIGN KEY (TypeID) REFERENCES `TypeQuestion` (TypeID)
);

DROP TABLE IF EXISTS `Answer`;
CREATE TABLE `Answer` (
	AnswerID			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Content				VARCHAR(100),
	QuestionID			TINYINT UNSIGNED NOT NULL,
	IsCorrect			ENUM('TRUE''FALSE'),
    CONSTRAINT FOREIGN KEY (QuestionID) REFERENCES `Question` (QuestionID) 
);

DROP TABLE IF EXISTS `Exam`;
CREATE TABLE  `Exam` (
	ExamID				TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Codes				VARCHAR(250) NOT NULL,
	Title				VARCHAR(250) NOT NULL, 
	CategoryID			TINYINT UNSIGNED,
	Duration			TINYINT UNSIGNED NOT NULL,
	CreatorID			INT UNSIGNED,
	CreateDate			DATETIME
);

DROP TABLE IF EXISTS `ExamQuestion`;
CREATE TABLE  ExamQuestion (
	ExamID				TINYINT UNSIGNED PRIMARY KEY NOT NULL,
    QuestionID			TINYINT UNSIGNED,
    CONSTRAINT FOREIGN KEY (ExamID) REFERENCES `Exam`(ExamID),
    CONSTRAINT FOREIGN KEY (QuestionID) REFERENCES `Question`(QuestionID)
);





		
    
    
 